# Generated by Django 2.2.3 on 2019-07-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='i_dislike',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='i_like',
            field=models.TextField(null=True),
        ),
    ]
