# Generated by Django 2.2.3 on 2019-07-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190722_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user1', models.IntegerField()),
                ('id_user2', models.IntegerField()),
                ('relationship', models.CharField(choices=[('FRIENDS', 'User1 is friend of User2'), ('FOLLOWER', 'User1 is follower of User2'), ('FOLLOWING', 'User1 is following by User2')], max_length=10)),
            ],
            options={
                'verbose_name': 'отношение между пользователями',
                'verbose_name_plural': 'отношения между пользователями',
            },
        ),
    ]
